# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/gonzo/fpu-fail/x-heep/hw/fpga/constraints/pynq-z2/pin_assign.xdc

# XDC: /home/gonzo/fpu-fail/x-heep/hw/fpga/constraints/pynq-z2/constraints.xdc

# Block Designs: bd/xilinx_clk_wizard/xilinx_clk_wizard.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_clk_wizard || ORIG_REF_NAME==xilinx_clk_wizard} -quiet] -quiet

# IP: bd/xilinx_clk_wizard/ip/xilinx_clk_wizard_clk_wiz_0_0/xilinx_clk_wizard_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==xilinx_clk_wizard_clk_wiz_0_0 || ORIG_REF_NAME==xilinx_clk_wizard_clk_wiz_0_0} -quiet] -quiet

# XDC: /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/openhwgroup.org_systems_core-v-mini-mcu_0.gen/sources_1/bd/xilinx_clk_wizard/xilinx_clk_wizard_ooc.xdc
