# Auto-generated project tcl file

# Must be set before creating the project otherwise it is ignored.
# Allows the user to provide local path to board files.
set_param board.repoPaths {  ../../../hw/fpga/board_files/vendor/esl_epfl_pynq_z2_board_files }
create_project openhwgroup.org_systems_core-v-mini-mcu_0 -force

set_property part xc7z020clg400-1 [current_project]
set_property board_part tul.com.tw:pynq-z2:part0:1.0 [current_project]

set_property generic {COREV_PULP=0 FPU=0 X_EXT=1 } [get_filesets sources_1]

set_property verilog_define {FPGA_XILINX=1 SYNTHESIS=1 } [get_filesets sources_1]
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/top_earlgrey/rtl/top_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/spi_device/rtl/spi_device_reg_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/spi_device/rtl/spi_device_pkg.sv}
read_verilog -sv {generated/lowrisc_prim_prim_pkg-impl_0.1/prim_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_cipher_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_buf.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_flop.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_flop_en.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_xor2.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_ram_1p_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_22_16_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_22_16_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_28_22_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_28_22_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_39_32_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_39_32_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_64_57_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_64_57_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_72_64_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_72_64_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg_arb.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg_ext.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg_shadow.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_util_pkg.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/include/cv32e40x_pkg.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/if_c_obi.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/if_xif.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_if_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_csr.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_debug_triggers.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_cs_registers.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_register_file.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_register_file_wrapper.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_write_buffer.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_lsu_response_filter.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_load_store_unit.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_align_check.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_id_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_i_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_m_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_a_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_b_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_compressed_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_sequencer.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_alignment_buffer.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_prefetch_unit.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_mult.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_int_controller.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_clic_int_controller.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_ex_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_wb_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_div.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_alu.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_ff_one.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_popcnt.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_alu_b_cpop.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_controller_fsm.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_controller_bypass.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_controller.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_instr_obi_interface.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_data_obi_interface.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_prefetcher.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_sleep_unit.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_core.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_mpu.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_pma.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_pc_target.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_wpt.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_cluster_interconnect/rtl/tcdm_variable_latency_interconnect/xbar_varlat.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_cluster_interconnect/rtl/tcdm_variable_latency_interconnect/addr_dec_resp_mux_varlat.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/binary_to_gray.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cb_filter_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cc_onehot.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/clk_int_div.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/delta_counter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/ecc_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/edge_propagator_tx.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/exp_backoff.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/fifo_v3.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/gray_to_binary.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/isochronous_4phase_handshake.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/isochronous_spill_register.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/lfsr.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/lfsr_16bit.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/lfsr_8bit.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/mv_filter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/onehot_to_bin.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/plru_tree.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/popcount.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/rstgen_bypass.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/serial_deglitch.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/shift_reg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/shift_reg_gated.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/spill_register_flushable.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_demux.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_filter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_fork.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_intf.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_join.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_mux.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_throttle.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/sub_per_hash.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/sync.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/sync_wedge.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/unread.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/read.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_reset_ctrlr_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_2phase.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_4phase.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/addr_decode.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/addr_decode_napot.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cb_filter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_fifo_2phase.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/counter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/ecc_decode.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/ecc_encode.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/edge_detect.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/lzc.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/max_counter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/rstgen.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/spill_register.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_delay.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_fifo.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_fork_dynamic.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/clk_mux_glitch_free.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_reset_ctrlr.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_fifo_gray.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/fall_through_register.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/id_queue.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_to_mem.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_arbiter_flushable.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_fifo_optimal_wrap.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_register.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_xbar.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_fifo_gray_clearable.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/cdc_2phase_clearable.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/mem_to_banks.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_arbiter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/stream_omega_net.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/clock_divider_counter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/clk_div.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/find_first_one.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/generic_LFSR_8bit.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/prioarbiter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync_wedge.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/rrarbiter.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/clock_divider.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/fifo_v2.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/deprecated/fifo_v1.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/edge_propagator_ack.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/edge_propagator.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_common_cells/src/edge_propagator_rx.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_register_interface/src/reg_intf.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_register_interface/src/periph_to_reg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_register_interface/src/reg_demux.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_register_interface/src/reg_to_tlul.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dm_pkg.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/include/addr_map_rule_pkg.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/include/obi_pkg.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/include/reg_pkg.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/include/power_manager_pkg.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/include/core_v_mini_mcu_pkg.sv}
read_verilog -sv {../../../hw/ip/obi_fifo/obi_fifo.sv}
read_verilog -sv {../../../hw/ip/power_manager/rtl/power_manager_reg_pkg.sv}
read_verilog {../../../hw/vendor/yosyshq_picorv32/picosoc/spimemio.v}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_gateway.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_target.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_arbiter_ppc.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_arbiter_tree.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_arbiter_fixed.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subst_perm.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_present.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_prince.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_diff_decode.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_clock_mux2.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_ram_1p.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_lfsr.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_pkg.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_alu.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_branch_predict.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_compressed_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_controller.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_cs_registers.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_csr.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_counter.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_ex_block.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_fetch_fifo.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_id_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_if_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_load_store_unit.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_multdiv_fast.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_multdiv_slow.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_prefetch_buffer.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_pmp.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_wb.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_core.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_cast_multi.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_classifier.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_multi.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_fma_multi.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_noncomp.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_block.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_fmt_slice.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_rounding.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_top.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_th_32.sv}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v}
read_verilog {../../../hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/debug_rom/debug_rom.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/debug_rom/debug_rom_one_scratch.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dm_csrs.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dmi_cdc.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dmi_jtag.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dm_mem.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dm_obi_top.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dm_sba.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dm_top.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_riscv_dbg/src/dmi_bscane_tap.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_gpio/src/gpio_reg_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_gpio/src/gpio_reg_top.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_gpio/src/gpio.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_gpio/src/gpio_input_stage_no_clk_gates.sv}
read_verilog -sv {../../../hw/ip/boot_rom/boot_rom.sv}
read_verilog -sv {../../../hw/ip/dma/rtl/dma_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/dma/rtl/dma_reg_top.sv}
read_verilog -sv {../../../hw/ip/dma/rtl/dma.sv}
read_verilog -sv {../../../hw/ip/dma_subsystem/rtl/dma_subsystem.sv}
read_verilog -sv {../../../hw/ip/i2s/rtl/i2s_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/i2s/rtl/i2s_reg_top.sv}
read_verilog -sv {../../../hw/ip/i2s/rtl/i2s.sv}
read_verilog -sv {../../../hw/ip/i2s/rtl/i2s_core.sv}
read_verilog -sv {../../../hw/ip/i2s/rtl/i2s_rx_channel.sv}
read_verilog -sv {../../../hw/ip/i2s/rtl/i2s_ws_gen.sv}
read_verilog -sv {../../../hw/ip/i2s/rtl/event_counter.sv}
read_verilog -sv {../../../hw/system/pad_control/rtl/pad_control_reg_pkg.sv}
read_verilog -sv {../../../hw/system/pad_control/rtl/pad_control_reg_top.sv}
read_verilog -sv {../../../hw/system/pad_control/rtl/pad_control.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/pdm2pcm_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/pdm2pcm_reg_top.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/cic_combs.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/cic_comb.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/cic_integrators.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/decimator.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/halfband.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/cic_integrator.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/fir.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/pdm_core.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/pdm2pcm.sv}
read_verilog -sv {../../../hw/ip/pdm2pcm/rtl/pdm2pcm_window.sv}
read_verilog -sv {../../../hw/ip/obi_spimemio/rtl/obi_spimemio_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/obi_spimemio/rtl/obi_spimemio_reg_top.sv}
read_verilog -sv {../../../hw/ip/obi_spimemio/rtl/picorv32_pkg.sv}
read_verilog -sv {../../../hw/ip/obi_spimemio/rtl/obi_to_picorv32.sv}
read_verilog -sv {../../../hw/ip/obi_spimemio/rtl/obi_spimemio.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_apu_core_pkg.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_fpu_pkg.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_pkg.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_core_v_xif_pkg.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_alu.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_alu_div.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_ff_one.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_popcnt.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_compressed_decoder.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_controller.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_cs_registers.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_decoder.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_int_controller.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_ex_stage.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_hwloop_regs.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_id_stage.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_if_stage.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_load_store_unit.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_mult.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_prefetch_buffer.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_prefetch_controller.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_obi_interface.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_aligner.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_sleep_unit.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_core.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_apu_disp.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_x_disp.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_fifo.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_fp_wrapper.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_top.sv}
read_verilog -sv {../../../hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_register_file_ff.sv}
read_verilog -sv {generated/lowrisc_prim_buf-impl_0/prim_buf.sv}
read_verilog -sv {generated/lowrisc_prim_clock_mux2-impl_0/prim_clock_mux2.sv}
read_verilog -sv {generated/lowrisc_prim_flop-impl_0/prim_flop.sv}
read_verilog -sv {generated/lowrisc_prim_flop_2sync-impl_0/prim_flop_2sync.sv}
read_verilog -sv {generated/lowrisc_prim_flop_en-impl_0/prim_flop_en.sv}
read_verilog -sv {generated/lowrisc_prim_ram_1p-impl_0/prim_ram_1p.sv}
read_verilog -sv {generated/lowrisc_prim_xor2-impl_0/prim_xor2.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/include/cv32e40p_apu_core_pkg.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/include/cv32e40p_fpu_pkg.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/include/cv32e40p_pkg.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_alu.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_alu_div.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_ff_one.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_popcnt.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_compressed_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_controller.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_cs_registers.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_decoder.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_int_controller.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_ex_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_hwloop_regs.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_id_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_if_stage.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_load_store_unit.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_mult.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_prefetch_buffer.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_prefetch_controller.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_obi_interface.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_aligner.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_sleep_unit.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_core.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_apu_disp.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_fifo.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_fp_wrapper.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_top.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_register_file_ff.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_instr_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_prd_f_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_prd_zfinx_pkg.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_compressed_predecoder.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_controller.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_csr.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_decoder.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_predecoder.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_regfile.sv}
read_verilog -sv {../../../hw/vendor/pulp_platform_fpu_ss/src/fpu_ss.sv}
read_verilog -sv {../../../hw/fpga/sram_wrapper.sv}
read_verilog -sv {../../../hw/ip_examples/fpu_ss_wrapper/fpu_ss_wrapper.sv}
source {../../../hw/fpga/scripts/generate_sram.tcl}
read_verilog -sv {../../../hw/fpga/prim_xilinx_clk.sv}
read_verilog -sv {../../../hw/fpga/cv32e40p_xilinx_clock_gate.sv}
read_verilog -sv {../../../hw/fpga/cv32e40x_xilinx_clock_gate.sv}
read_verilog -sv {../../../hw/fpga/cve2_xilinx_clock_gate.sv}
read_verilog -sv {../../../hw/fpga/cv32e40px_xilinx_clock_gate.sv}
read_verilog -sv {../../../hw/fpga/pad_cell_input_xilinx.sv}
read_verilog -sv {../../../hw/fpga/pad_cell_output_xilinx.sv}
read_verilog -sv {../../../hw/fpga/pad_cell_inout_xilinx.sv}
read_verilog -sv {../../../hw/fpga/pad_cell_bypass_input_xilinx.sv}
read_verilog -sv {../../../hw/fpga/pad_cell_bypass_output_xilinx.sv}
source {../../../hw/fpga/scripts/pynq-z2/xilinx_generate_clk_wizard.tcl}
read_xdc {../../../hw/fpga/constraints/pynq-z2/pin_assign.xdc}
read_xdc {../../../hw/fpga/constraints/pynq-z2/constraints.xdc}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_alert_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_alert_receiver.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_alert_sender.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_ram_1p_adv.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_fifo_async.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_fifo_sync.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_clock_gating_sync.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_esc_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_esc_receiver.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_esc_sender.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sram_arbiter.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_slicer.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sync_reqack.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sync_reqack_data.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sync_slow_fast.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_keccak.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_packer.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_packer_fifo.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_gate_gen.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_pulse_sync.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_filter.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_filter_ctr.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_intr_hw.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_fifo_sync.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_fifo_async.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_assert.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_err.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_assert_multiple.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_reg_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_cmd_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_shift_register.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_byte_select.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_byte_merge.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_fsm.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_core.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_command_queue.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_data_fifos.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_reg_top.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_window.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_ram_1p_scr.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_err_resp.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_socket_1n.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv}
read_verilog -sv {../../../hw/ip/soc_ctrl/rtl/soc_ctrl_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/soc_ctrl/rtl/soc_ctrl_reg_top.sv}
read_verilog -sv {../../../hw/ip/soc_ctrl/rtl/soc_ctrl.sv}
read_verilog -sv {../../../hw/ip/fast_intr_ctrl/rtl/fast_intr_ctrl_reg_pkg.sv}
read_verilog -sv {../../../hw/ip/fast_intr_ctrl/rtl/fast_intr_ctrl_reg_top.sv}
read_verilog -sv {../../../hw/ip/fast_intr_ctrl/rtl/fast_intr_ctrl.sv}
read_verilog -sv {../../../hw/ip/power_manager/rtl/power_manager_reg_top.sv}
read_verilog -sv {../../../hw/ip/power_manager/rtl/power_manager_counter_sequence.sv}
read_verilog -sv {../../../hw/ip/power_manager/rtl/power_manager_sequence.sv}
read_verilog -sv {../../../hw/ip/power_manager/rtl/power_manager.sv}
read_verilog -sv {../../../hw/ip/power_manager/rtl/reg_to_counter.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_adapter_reg.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_register_file_ff.sv}
read_verilog -sv {../../../hw/vendor/openhwgroup_cv32e20/rtl/cve2_top.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_reg_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_reg_top.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_core.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_fsm.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_reg_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_reg_top.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_top.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/timer_core.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/rv_timer.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_reg_pkg.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_reg_top.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_rx.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_tx.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_core.sv}
read_verilog -sv {../../../hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/core_v_mini_mcu.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/cpu_subsystem.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/memory_subsystem.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/xbar_varlat_one_to_n.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/xbar_varlat_n_to_one.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/system_bus.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/system_xbar.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/spi_subsystem.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/debug_subsystem.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/peripheral_subsystem.sv}
read_verilog -sv {../../../hw/core-v-mini-mcu/ao_peripheral_subsystem.sv}
read_verilog -sv {../../../hw/system/x_heep_system.sv}
read_verilog -sv {../../../hw/system/pad_ring.sv}
read_verilog -sv {../../../hw/fpga/xilinx_core_v_mini_mcu_wrapper.sv}

set_property include_dirs [list ../../../hw/vendor/openhwgroup_cv32e20/vendor/lowrisc_ip/dv/sv/dv_utils ../../../hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl ../../../hw/vendor/pulp_platform_common_cells/include ../../../hw/vendor/pulp_platform_register_interface/include ../../../hw/vendor/openhwgroup_cv32e20/rtl .] [get_filesets sources_1]
set_property top xilinx_core_v_mini_mcu_wrapper [current_fileset]
set_property source_mgmt_mode None [current_project]


