fusesoc-deps := \
  /home/gonzo/fpu-fail/x-heep/core-v-mini-mcu.core \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/core_v_mini_mcu.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/cpu_subsystem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/memory_subsystem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/xbar_varlat_one_to_n.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/xbar_varlat_n_to_one.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/system_bus.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/system_xbar.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/spi_subsystem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/debug_subsystem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/peripheral_subsystem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/ao_peripheral_subsystem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/system/x_heep_system.sv \
  /home/gonzo/fpu-fail/x-heep/hw/system/pad_ring.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/xilinx_core_v_mini_mcu_wrapper.sv \
  /home/gonzo/fpu-fail/x-heep/core-v-mini-mcu-fpga.core \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/sram_wrapper.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip_examples/fpu_ss_wrapper/fpu_ss_wrapper.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/scripts/generate_sram.tcl \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/prim_xilinx_clk.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/cv32e40p_xilinx_clock_gate.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/cv32e40x_xilinx_clock_gate.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/cve2_xilinx_clock_gate.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/cv32e40px_xilinx_clock_gate.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/pad_cell_input_xilinx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/pad_cell_output_xilinx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/pad_cell_inout_xilinx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/pad_cell_bypass_input_xilinx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/pad_cell_bypass_output_xilinx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/scripts/pynq-z2/xilinx_generate_clk_wizard.tcl \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/constraints/pynq-z2/pin_assign.xdc \
  /home/gonzo/fpu-fail/x-heep/hw/fpga/constraints/pynq-z2/constraints.xdc \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_instr_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_prd_f_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_prd_zfinx_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_compressed_predecoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_csr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_predecoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss_regfile.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpu_ss/src/fpu_ss.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_cast_multi.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_classifier.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_multi.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_fma_multi.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_noncomp.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_block.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_fmt_slice.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_opgroup_multifmt_slice.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_rounding.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/src/fpnew_divsqrt_th_32.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/clk/rtl/gated_clk_cell.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ctrl.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_ff1.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_pack_single.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_prepare.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_round_single.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_special.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_srt_single.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fdsu/rtl/pa_fdsu_top.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_dp.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_frbus.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_fpnew/vendor/opene906/E906_RTL_FACTORY/gen_rtl/fpu/rtl/pa_fpu_src_type.v \
  /home/gonzo/fpu-fail/x-heep/hw/system/pad_control/pad_control.core \
  /home/gonzo/fpu-fail/x-heep/hw/system/pad_control/rtl/pad_control_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/system/pad_control/rtl/pad_control_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/system/pad_control/rtl/pad_control.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/pdm2pcm.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/pdm2pcm_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/pdm2pcm_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/cic_combs.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/cic_comb.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/cic_integrators.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/decimator.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/halfband.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/cic_integrator.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/fir.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/pdm_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/pdm2pcm.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/pdm2pcm/rtl/pdm2pcm_window.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_fifo/obi_fifo.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_fifo/obi_fifo.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/fast_intr_ctrl/fast_intr_ctrl.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/fast_intr_ctrl/rtl/fast_intr_ctrl_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/fast_intr_ctrl/rtl/fast_intr_ctrl_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/fast_intr_ctrl/rtl/fast_intr_ctrl.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_clock_gating_sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_esc_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_esc_receiver.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_esc_sender.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sram_arbiter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_slicer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sync_reqack.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sync_reqack_data.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_sync_slow_fast.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_keccak.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_packer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_packer_fifo.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_gate_gen.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_pulse_sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_filter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_filter_ctr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_intr_hw.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_xor2.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_xor2-impl_0/prim_xor2.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_xor2-impl_0/prim_xor2.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/prim_generic_xor2.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_xor2.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/primgen.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_cipher.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subst_perm.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_present.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_prince.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_cipher_pkg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_cipher_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_subreg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg_arb.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg_ext.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_subreg_shadow.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_alert.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_alert_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_alert_receiver.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_alert_sender.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_fifo.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_fifo_async.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_fifo_sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_arbiter.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_arbiter_ppc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_arbiter_tree.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_arbiter_fixed.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_flop_2sync.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_flop_2sync-impl_0/prim_flop_2sync.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_flop_2sync-impl_0/prim_flop_2sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/prim_generic_flop_2sync.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_flop_2sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_flop_en.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_flop_en-impl_0/prim_flop_en.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_flop_en-impl_0/prim_flop_en.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/prim_generic_flop_en.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_flop_en.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_flop.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_flop-impl_0/prim_flop.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_flop-impl_0/prim_flop.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/prim_generic_flop.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_flop.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_buf.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_buf-impl_0/prim_buf.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_buf-impl_0/prim_buf.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/prim_generic_buf.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_buf.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_clock_mux2.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_clock_mux2-impl_0/prim_clock_mux2.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_clock_mux2-impl_0/prim_clock_mux2.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/prim_generic_clock_mux2.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_clock_mux2.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_pkg.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_prim_pkg-impl_0.1/prim_pkg.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_prim_pkg-impl_0.1/prim_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_diff_decode.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_diff_decode.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_util.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_util_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_assert.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_assert.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_assert_dummy_macros.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_assert_yosys_macros.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_assert_standard_macros.svh \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/power_manager.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/rtl/power_manager_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/rtl/power_manager_counter_sequence.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/rtl/power_manager_sequence.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/rtl/power_manager.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/rtl/reg_to_counter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/power_manager_pkg.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/power_manager/rtl/power_manager_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/i2s.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/rtl/i2s_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/rtl/i2s_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/rtl/i2s.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/rtl/i2s_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/rtl/i2s_rx_channel.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/rtl/i2s_ws_gen.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/i2s/rtl/event_counter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/dma_subsystem/dma_subsystem.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/dma_subsystem/rtl/dma_subsystem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/dma/dma.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/dma/rtl/dma_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/dma/rtl/dma_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/dma/rtl/dma.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/boot_rom/boot_rom.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/boot_rom/boot_rom.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_spimemio/obi_spimemio.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_spimemio/rtl/obi_spimemio_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_spimemio/rtl/obi_spimemio_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_spimemio/rtl/picorv32_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_spimemio/rtl/obi_to_picorv32.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/obi_spimemio/rtl/obi_spimemio.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/yosyshq_picorv32_spimemio.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/yosyshq_picorv32/picosoc/spimemio.v \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/i2c/i2c.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c_fsm.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/i2c/rtl/i2c.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/tlul.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/adapter_reg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_adapter_reg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/trans_intg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/common.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_fifo_sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_fifo_async.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_assert.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_err.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_assert_multiple.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/headers.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_secded.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_22_16_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_22_16_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_28_22_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_28_22_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_39_32_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_39_32_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_64_57_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_64_57_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_72_64_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_72_64_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/socket_1n.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_err_resp.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/tlul/rtl/tlul_socket_1n.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/top_earlgrey/top_pkg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/top_earlgrey/rtl/top_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/spi_host.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_cmd_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_shift_register.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_byte_select.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_byte_merge.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_fsm.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_command_queue.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_data_fifos.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host_window.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan_spi_host/rtl/spi_host.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/spi_device/spi_device_pkg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/spi_device/rtl/spi_device_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/spi_device/rtl/spi_device_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rv_timer.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/rv_timer_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/timer_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_timer/rtl/rv_timer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rv_plic.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rv_plic_component.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_gateway.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/rv_plic/rtl/rv_plic_target.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/uart/uart.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_rx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_tx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/uart/rtl/uart.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/soc_ctrl/openhwgroup_soc_ctrl.core \
  /home/gonzo/fpu-fail/x-heep/hw/ip/soc_ctrl/rtl/soc_ctrl_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/soc_ctrl/rtl/soc_ctrl_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/ip/soc_ctrl/rtl/soc_ctrl.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_register_interface.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_register_interface/include/register_interface/assign.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_register_interface/include/register_interface/typedef.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_register_interface/src/reg_intf.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_register_interface/src/periph_to_reg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_register_interface/src/reg_demux.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_register_interface/src/reg_to_tlul.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/debug_rom/debug_rom.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/debug_rom/debug_rom_one_scratch.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dm_csrs.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dmi_cdc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dmi_jtag.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dm_mem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dm_obi_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dm_sba.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dm_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dmi_bscane_tap.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg_pkg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_riscv_dbg/src/dm_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_tech_cells_generic.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_cluster_interconnect.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_cluster_interconnect/rtl/tcdm_variable_latency_interconnect/xbar_varlat.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_cluster_interconnect/rtl/tcdm_variable_latency_interconnect/addr_dec_resp_mux_varlat.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/common_cells.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/include/common_cells/registers.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/include/common_cells/assertions.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/binary_to_gray.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cb_filter_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cc_onehot.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cf_math_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/clk_int_div.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/delta_counter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/ecc_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/edge_propagator_tx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/exp_backoff.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/fifo_v3.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/gray_to_binary.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/isochronous_4phase_handshake.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/isochronous_spill_register.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/lfsr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/lfsr_16bit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/lfsr_8bit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/mv_filter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/onehot_to_bin.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/plru_tree.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/popcount.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/rr_arb_tree.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/rstgen_bypass.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/serial_deglitch.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/shift_reg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/shift_reg_gated.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/spill_register_flushable.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_demux.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_filter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_fork.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_intf.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_join.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_mux.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_throttle.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/sub_per_hash.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/sync_wedge.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/unread.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/read.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_reset_ctrlr_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_2phase.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_4phase.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/addr_decode.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/addr_decode_napot.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cb_filter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_fifo_2phase.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/counter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/ecc_decode.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/ecc_encode.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/edge_detect.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/lzc.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/max_counter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/rstgen.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/spill_register.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_delay.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_fifo.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_fork_dynamic.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/clk_mux_glitch_free.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_reset_ctrlr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_fifo_gray.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/fall_through_register.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/id_queue.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_to_mem.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_arbiter_flushable.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_fifo_optimal_wrap.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_register.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_xbar.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_fifo_gray_clearable.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/cdc_2phase_clearable.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/mem_to_banks.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_arbiter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/stream_omega_net.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/clock_divider_counter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/clk_div.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/find_first_one.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/generic_LFSR_8bit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/generic_fifo.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/prioarbiter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/pulp_sync_wedge.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/rrarbiter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/clock_divider.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/fifo_v2.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/deprecated/fifo_v1.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/edge_propagator_ack.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/edge_propagator.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_common_cells/src/edge_propagator_rx.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_gpio.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_gpio/src/gpio_reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_gpio/src/gpio_reg_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_gpio/src/gpio.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/pulp_platform_gpio/src/gpio_input_stage_no_clk_gates.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_apu_core_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_fpu_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/include/cv32e40px_core_v_xif_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_alu.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_alu_div.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_ff_one.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_popcnt.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_compressed_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_cs_registers.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_int_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_ex_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_hwloop_regs.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_id_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_if_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_load_store_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_mult.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_prefetch_buffer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_prefetch_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_obi_interface.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_aligner.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_sleep_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_apu_disp.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_x_disp.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_fifo.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_fp_wrapper.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/esl_epfl_cv32e40px/rtl/cv32e40px_register_file_ff.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/cve2_top.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_register_file_ff.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_ram_1p_scr.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_ram_1p_scr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_lfsr.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_lfsr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_ram_1p_adv.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_ram_1p_adv.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_ram_1p.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_ram_1p-impl_0/prim_ram_1p.core \
  /home/gonzo/fpu-fail/x-heep/build/openhwgroup.org_systems_core-v-mini-mcu_0/pynq-z2-vivado/generated/lowrisc_prim_ram_1p-impl_0/prim_ram_1p.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/prim_generic_ram_1p.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim_generic/rtl/prim_generic_ram_1p.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_util_memload.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_util_memload.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/prim_ram_1p_pkg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/rtl/prim_ram_1p_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/cve2_core.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_alu.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_branch_predict.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_compressed_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_cs_registers.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_csr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_counter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_ex_block.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_fetch_fifo.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_id_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_if_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_load_store_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_multdiv_fast.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_multdiv_slow.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_prefetch_buffer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_pmp.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_wb.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_pmp_reset_default.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/vendor/lowrisc_ip/dv/sv/dv_utils/dv_fcov_macros.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/vendor/lowrisc_ip/dv/sv/dv_utils/dv_fcov_macros.svh \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/cve2_pkg.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e20/rtl/cve2_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/include/cv32e40x_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/if_c_obi.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/if_xif.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_if_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_csr.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_debug_triggers.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_cs_registers.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_register_file.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_register_file_wrapper.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_write_buffer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_lsu_response_filter.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_load_store_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_align_check.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_id_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_i_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_m_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_a_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_b_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_compressed_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_sequencer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_alignment_buffer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_prefetch_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_mult.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_int_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_clic_int_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_ex_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_wb_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_div.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_alu.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_ff_one.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_popcnt.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_alu_b_cpop.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_controller_fsm.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_controller_bypass.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_instr_obi_interface.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_data_obi_interface.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_prefetcher.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_sleep_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_mpu.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_pma.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_pc_target.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40x/rtl/cv32e40x_wpt.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/include/cv32e40p_apu_core_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/include/cv32e40p_fpu_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/include/cv32e40p_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_alu.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_alu_div.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_ff_one.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_popcnt.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_compressed_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_cs_registers.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_decoder.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_int_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_ex_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_hwloop_regs.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_id_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_if_stage.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_load_store_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_mult.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_prefetch_buffer.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_prefetch_controller.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_obi_interface.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_aligner.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_sleep_unit.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_core.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_apu_disp.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_fifo.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_fp_wrapper.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_top.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/openhwgroup_cv32e40p/rtl/cv32e40p_register_file_ff.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/include/x-heep_packages.core \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/include/addr_map_rule_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/include/obi_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/include/reg_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/include/power_manager_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/core-v-mini-mcu/include/core_v_mini_mcu_pkg.sv \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/primgen.core \
  /home/gonzo/fpu-fail/x-heep/hw/vendor/lowrisc_opentitan/hw/ip/prim/util/primgen.py
